---
title: "HNC_CD8T_AEG"
author: "Athena Golfinos"
date: "8/26/2021"
output: html_document
---

```{r INPUT VARIABLES}
#this should be a nice descriptive name (in string form) for your object
obj <- 'HNC_CD8_AEG'

#string of the metadata column where your resolution is found
res <- 'AEG_CD8_RNA_snn_res.0.1'

#number of principal components to use--please provide a range from 1:X
PCs <- 1:15

#please provide the full dataframe path to your resolution
res_loc <- CD8@meta.data$AEG_CD8_RNA_snn_res.0.1

#DE genes clusters--see below

#if you want to use all clusters uncomment this line
clusts <- unique(res_loc)
clusts <- sort(clusts)

#input select clusters here in vector form if you want to subset
#clusts <- c('1', '3', '5', '19', '22')
```

```{r input packages}
library(Seurat)
library(patchwork)
library(dplyr)
library(ggplot2)
library(clustree)
library(topGO)
library(biomaRt)
library(SeuratWrappers)
library(stringr)
```
```{r read in}
load(file = "/Users/agolfinos/Desktop/Seurat_HNC_CD8.rda")
DimPlot(cd8, group.by = "global.cluster", label = TRUE, label.box = TRUE)
```
```{r clustree}
clustree(cd8, prefix = 'AEG_CD8_RNA_snn_res.')
```
```{r QC calculations}
#cd8[['percent.mt']] <- PercentageFeatureSet(cd8, pattern = '^MT-')

#VlnPlot(cd8, features = c('nFeature_RNA', 'nCount_RNA', 'percent.mt'), ncol = 3)

#plot1 <- FeatureScatter(cd8, feature1 = 'nCount_RNA', feature2 = 'percent.mt')
#plot2 <- FeatureScatter(cd8, feature1 = 'nCount_RNA', feature2 = 'nFeature_RNA')
#plot1 + plot2

#cd8 <- subset(cd8, subset = nFeature_RNA > 200 & nFeature_RNA < 4000)

#cd8 <- NormalizeData(cd8, normalization.method = 'LogNormalize', scale.factor = 10000)

#all.genes <- rownames(cd8)
cd8 <- ScaleData(cd8, features = all.genes, vars.to.regress = c('percent.mt'))
```

