---
title: "Violin plots"
author: "Athena Golfinos"
date: "2/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
test1 <- VlnPlot(hnc, features = c('IL12B'), split.by = 'hpv_status', pt.size = 0, idents = 'DC3_LAMP3')
test2 <- VlnPlot(hnc, features = c('CCL17'), split.by = 'hpv_status', pt.size = 0, idents = 'DC3_LAMP3')
test3 <- VlnPlot(hnc, features = c('IRF8'), split.by = 'hpv_status', pt.size = 0, idents = 'DC3_LAMP3')
test4 <- VlnPlot(hnc, features = c('CADM1'), split.by = 'hpv_status', pt.size = 0, idents = 'DC3_LAMP3')
cowplot::plot_grid(test1, test2, test3, test4)

ggsave('/Users/agolfinos/Desktop/mregDC1_markers.png')

test5 <- VlnPlot(hnc, features = c('SIRPA'), split.by = 'hpv_status', pt.size = 0, idents = 'DC3_LAMP3')
test6 <- VlnPlot(hnc, features = c('FCER1G'), split.by = 'hpv_status', pt.size = 0, idents = 'DC3_LAMP3')
cowplot::plot_grid(test5, test6)

ggsave('/Users/agolfinos/Desktop/mregDC2_markers.png')

test1 <- VlnPlot(hnc, features = c('CXCL9'), split.by = 'hpv_status', pt.size = 0, idents = 'DC3_LAMP3')
test2 <- VlnPlot(hnc, features = c('CXCL10'), split.by = 'hpv_status', pt.size = 0, idents = 'DC3_LAMP3')
test3 <- VlnPlot(hnc, features = c('CXCL11'), split.by = 'hpv_status', pt.size = 0, idents = 'DC3_LAMP3')
cowplot::plot_grid(test1, test2, test3)

ggsave('/Users/agolfinos/Desktop/cxcl_markers.png')
```

